plugins:
  cakeday_enabled:
    default: true
    client: true
  cakeday_emoji:
    default: 'cake'
    client: true
  cakeday_birthday_enabled:
    default: true
    client: true
  cakeday_birthday_emoji:
    default: 'birthday'
    client: true
  cakeday_birthday_show_year:
    default: false
    client: true
  cakeday_birthday_formatdmy:
    default: false
    client: true
